services:
  db:
    image: postgis/postgis:17-3.5
    container_name: playas_postgis
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data: